CREATE TABLE quests (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(80) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(400) NOT NULL,
    quest_type VARCHAR(30) NOT NULL,
    job_restriction VARCHAR(30),
    prerequisite_quest_id BIGINT,
    required_target_type VARCHAR(40) NOT NULL,
    required_target_id BIGINT,
    required_count INTEGER NOT NULL,
    reward_beads INTEGER NOT NULL,
    reward_exp INTEGER NOT NULL,
    reward_item_id BIGINT,
    reward_title VARCHAR(60),
    unlock_feature VARCHAR(40),
    is_promotion_quest BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_quests_code UNIQUE (code),
    CONSTRAINT fk_quests_prerequisite FOREIGN KEY (prerequisite_quest_id) REFERENCES quests (id) ON DELETE SET NULL
);

CREATE TABLE character_quests (
    id BIGSERIAL PRIMARY KEY,
    character_id BIGINT NOT NULL,
    quest_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    progress_count INTEGER NOT NULL,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_character_quests_character FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    CONSTRAINT fk_character_quests_quest FOREIGN KEY (quest_id) REFERENCES quests (id) ON DELETE CASCADE,
    CONSTRAINT uk_character_quests_character_quest UNIQUE (character_id, quest_id)
);

CREATE INDEX idx_character_quests_character ON character_quests (character_id);

CREATE TABLE job_classes (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    job VARCHAR(30) NOT NULL,
    cost_beads INTEGER NOT NULL,
    reward_exp INTEGER NOT NULL,
    repeatable BOOLEAN NOT NULL,
    unlock_level INTEGER NOT NULL,
    unlock_promotion_tier VARCHAR(30) NOT NULL,
    CONSTRAINT uk_job_classes_job_name UNIQUE (job, name)
);

CREATE TABLE job_class_stat_rewards (
    id BIGSERIAL PRIMARY KEY,
    job_class_id BIGINT NOT NULL,
    stat_type VARCHAR(40) NOT NULL,
    reward_amount INTEGER NOT NULL,
    CONSTRAINT fk_job_class_stat_rewards_class FOREIGN KEY (job_class_id) REFERENCES job_classes (id) ON DELETE CASCADE
);

INSERT INTO quests (
    code,
    title,
    description,
    quest_type,
    job_restriction,
    prerequisite_quest_id,
    required_target_type,
    required_target_id,
    required_count,
    reward_beads,
    reward_exp,
    reward_item_id,
    reward_title,
    unlock_feature,
    is_promotion_quest,
    sort_order
) VALUES
    (
        'NEW_ROOM_NEW_START',
        'New Room, New Start',
        'Take your first breath in Vanilla Dream and settle into your new room.',
        'TALK',
        NULL,
        NULL,
        'CHARACTER_CREATED',
        NULL,
        1,
        50,
        20,
        NULL,
        NULL,
        NULL,
        FALSE,
        1
    ),
    (
        'EXPLORE_THE_MAIN_PLAZA',
        'Explore the Main Plaza',
        'Step into the city hub and get familiar with the plaza atmosphere.',
        'VISIT',
        NULL,
        (SELECT id FROM quests WHERE code = 'NEW_ROOM_NEW_START'),
        'MAIN_PLAZA_VISIT',
        NULL,
        1,
        70,
        20,
        NULL,
        NULL,
        'ACADEMY',
        FALSE,
        2
    ),
    (
        'MEET_YOUR_JOB_MENTOR',
        'Meet Your Job Mentor',
        'Choose a career path so the academy can match you with a mentor.',
        'TALK',
        NULL,
        (SELECT id FROM quests WHERE code = 'EXPLORE_THE_MAIN_PLAZA'),
        'JOB_SELECTED',
        NULL,
        1,
        80,
        20,
        NULL,
        NULL,
        'ACADEMY',
        FALSE,
        3
    ),
    (
        'TAKE_YOUR_FIRST_CLASS',
        'Take Your First Class',
        'Enroll in one academy class and begin building your professional basics.',
        'TAKE_CLASS',
        NULL,
        (SELECT id FROM quests WHERE code = 'MEET_YOUR_JOB_MENTOR'),
        'CLASS_TAKE',
        NULL,
        1,
        90,
        40,
        NULL,
        NULL,
        'MINIGAMES',
        FALSE,
        4
    ),
    (
        'FIRST_PART_TIME_JOB',
        'First Part-Time Job',
        'Complete one part-time minigame shift to earn your first workday income.',
        'MINIGAME',
        NULL,
        (SELECT id FROM quests WHERE code = 'TAKE_YOUR_FIRST_CLASS'),
        'MINIGAME_PLAY',
        NULL,
        1,
        120,
        60,
        NULL,
        NULL,
        'MINIGAMES',
        FALSE,
        5
    ),
    (
        'ENTER_THE_SHOPPING_STREET',
        'Enter the Shopping Street',
        'Visit the shopping street and see what style pieces are available in town.',
        'VISIT',
        NULL,
        (SELECT id FROM quests WHERE code = 'TAKE_YOUR_FIRST_CLASS'),
        'SHOPPING_STREET_VISIT',
        NULL,
        1,
        100,
        40,
        NULL,
        NULL,
        'SHOPPING_STREET',
        FALSE,
        6
    ),
    (
        'COMPLETE_YOUR_FIRST_OUTFIT',
        'Complete Your First Outfit',
        'Buy a fashion item to start shaping your first complete look.',
        'PURCHASE',
        NULL,
        (SELECT id FROM quests WHERE code = 'ENTER_THE_SHOPPING_STREET'),
        'ITEM_PURCHASE',
        NULL,
        1,
        150,
        70,
        NULL,
        'Styled Rookie',
        NULL,
        FALSE,
        7
    ),
    (
        'TOWARD_APPRENTICE',
        'Toward Apprentice',
        'Reach level 3 to prove you are ready for the apprentice preparation track.',
        'PROMOTION_PREP',
        NULL,
        (SELECT id FROM quests WHERE code = 'TAKE_YOUR_FIRST_CLASS'),
        'LEVEL_REACHED',
        NULL,
        3,
        180,
        90,
        NULL,
        'Career Starter',
        'PROMOTION',
        TRUE,
        8
    );

INSERT INTO job_classes (name, job, cost_beads, reward_exp, repeatable, unlock_level, unlock_promotion_tier) VALUES
    ('Fashion Illustration Basics', 'DESIGNER', 60, 120, TRUE, 1, 'BEGINNER'),
    ('Fabric Sense Training', 'DESIGNER', 65, 120, TRUE, 1, 'BEGINNER'),
    ('Color Balance Intro', 'DESIGNER', 70, 120, TRUE, 2, 'BEGINNER'),
    ('Product Categorization Basics', 'MD', 60, 120, TRUE, 1, 'BEGINNER'),
    ('Sales Flow Understanding', 'MD', 65, 120, TRUE, 1, 'BEGINNER'),
    ('Customer Communication Practice', 'MD', 70, 120, TRUE, 2, 'BEGINNER'),
    ('Basic Walking Balance', 'MODEL', 60, 120, TRUE, 1, 'BEGINNER'),
    ('Pose Training', 'MODEL', 65, 120, TRUE, 1, 'BEGINNER'),
    ('Facial Expression Intro', 'MODEL', 70, 120, TRUE, 2, 'BEGINNER');

INSERT INTO job_class_stat_rewards (job_class_id, stat_type, reward_amount) VALUES
    ((SELECT id FROM job_classes WHERE job = 'DESIGNER' AND name = 'Fashion Illustration Basics'), 'CREATIVITY', 2),
    ((SELECT id FROM job_classes WHERE job = 'DESIGNER' AND name = 'Fabric Sense Training'), 'PATTERN_SENSE', 2),
    ((SELECT id FROM job_classes WHERE job = 'DESIGNER' AND name = 'Color Balance Intro'), 'COLOR_SENSE', 2),
    ((SELECT id FROM job_classes WHERE job = 'MD' AND name = 'Product Categorization Basics'), 'MERCHANDISING', 2),
    ((SELECT id FROM job_classes WHERE job = 'MD' AND name = 'Sales Flow Understanding'), 'ANALYSIS', 2),
    ((SELECT id FROM job_classes WHERE job = 'MD' AND name = 'Customer Communication Practice'), 'COMMUNICATION', 2),
    ((SELECT id FROM job_classes WHERE job = 'MODEL' AND name = 'Basic Walking Balance'), 'WALKING', 2),
    ((SELECT id FROM job_classes WHERE job = 'MODEL' AND name = 'Pose Training'), 'POSE', 2),
    ((SELECT id FROM job_classes WHERE job = 'MODEL' AND name = 'Facial Expression Intro'), 'EXPRESSION', 2);
